print("        X")
print("       XXX")
print("      XXXXX")
print("     XXXXXXX")
print("    XXXXXXXXX")
print("   XXXXXXXXXXX")
print("  XXXXXXXXXXXXX")
print(" XXXXXXXXXXXXXXX")
print("XXXXXXXXXXXXXXXXX")
print("       XX")
print("       XX")
print("      XXXX")